---
- name: Remove temporary files
  file: path={{ item }} state=absent
  with_items:
   - /root/ldap.inf
   - /root/consumer_replica.ldif
   - /root/replication_user.ldif
   - /root/supplier_changelog.ldif
   - /root/supplier_replica.ldif
   - /root/supplier_replication_agreement.ldif
