---
# Configuration type
# if it is set - preparation and 389-ds configuration activities will be skipped (usually to add a new replication agreement)
 skip_config: false

# General 389-ds settings
 password: Admin123
 suffix: dc=prf,dc=rs
 rootdn: cn=root
 serverid: ldapsrv

# Admin server settings
 admin_password: Admin123
 admin_domain: prf.rs

# Replication supplier settings
 supplier: false
 replication_nsds5replicaid: 7
 agreement_name: ExampleAgreement
 consumer_host: ldap.prf.rs
 init_consumer: true

# Replication consumer settings
 consumer: true
 # this will create LDAP user cn=replmanager,cn=config
 replication_user: replmanager
 replication_user_password: Admin123
