---
 - name: Configure crontab
   hosts: Cronod 
   #become: yes
   #become_method: su
   tasks:
     - name: Copy script crontabs
       copy:
         src: "/home/felipeaguiar/Documents/Linux/code/Ansible/ansible/get_sec_update.sh"
         dest: "/usr/local/bin/get_sec_update.sh"
         mode: 0775

     - name: Crate job crontab
       cron:
         name: get_sec_update
         hour: 12
         minute: 0
         user: root
         job: /usr/local/bin/get_sec_update.sh
         cron_file: get-security-update
     - name: Restart crond
       service:
          name: cron
          state: restarted
